[project]
name = "csa-lab-4"
version = "0.1.0"
description = "CSA лабораторная работа №4"
requires-python = ">=3.14"
dependencies = [
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
    "mypy>=1.16.0",
    "pytest>=9.0.3",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM", "C4", "RUF", "PL"]

[tool.ruff.lint.per-file-ignores]
"src/machine/simulator/simulator.py"   = ["B008"]
"src/machine/simulator/log_presenter.py" = ["PLR2004"]
"src/config_loader.py"                 = ["SIM108"]
"src/main.py"                          = ["PLR2004", "E402"]
"src/translator/translator.py"         = ["PLR0912", "PLR0915", "F403", "F405"]
"src/translator/definition.py"         = ["PLR0912", "PLR0915"]
"src/translator/parser.py"             = ["PLR0911", "PLR0912"]
"src/machine/processor/data_path.py"   = ["PLR0912", "PLR0915"]
"src/binary.py"                        = ["PLR0913"]

[tool.mypy]
strict = true
explicit_package_bases = true
namespace_packages = true

[[tool.mypy.overrides]]
module = "yaml"
ignore_missing_imports = true
